tempo:
  memBallastSizeMbs: 256
  overrides:
    defaults:
      global:
        max_bytes_per_trace: 5e+6
  querier:
    max_concurrent_queries: 5
  resources:
    requests:
      memory: "2Gi"
      cpu: "500m"
    limits:
      memory: "3Gi"
      cpu: "1500m"
  storage:
    trace:
      backend: s3
      s3:
        endpoint: s3.xorcloud.net
        bucket: trace-tempo
        access_key: CBV9EVOGVK7B2QQDTGRO
        secret_key: EPSR7nAKICASKtdJvnVbfjBBwOFuzS5bPOBkTilH
        insecure: false
